version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: example_db
    volumes:
      - wordpress:/var/www/html
      - ./wish-to-go:/var/www/html/wp-content/plugins/wish-to-go

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: example_db
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: